// Generated by `seedcord codegen`. Do not edit by hand.
// Run `seedcord codegen` after changing your commands, plugins, or emoji config.

import type Bot from './bot';

// prettier-ignore
declare module '@seedcord/gateway' {
    interface Core {
        storage: (typeof Bot)['storage'];
    }
    interface SlashRegistry {
        ping: { options: { detailed: { kind: 'boolean'; required: false } }; cache: 'cached' };
        roll: { options: {}; cache: 'cached' };
        'storage/delete': { options: { key: { kind: 'string'; required: true }; display: { kind: 'boolean'; required: false } }; cache: 'cached' };
        'storage/list': { options: { prefix: { kind: 'string'; required: false } }; cache: 'cached' };
        'storage/read': { options: { key: { kind: 'string'; required: true } }; cache: 'cached' };
        'storage/write': { options: { key: { kind: 'string'; required: true }; value: { kind: 'string'; required: true }; append: { kind: 'boolean'; required: false } }; cache: 'cached' };
    }
    interface UserContextMenuRegistry {

    }
    interface MessageContextMenuRegistry {

    }
    interface EmojiMap {

    }
}

export {};
